
apis:
  container: "http://127.0.0.1:8000/container"
  container_model: "http://127.0.0.1:8000/containermodel"
  update_endpoint: "http://127.0.0.1:8000/updateEndpoint"
  model_master_config: "http://127.0.0.1:8000/getModelMasterbyId"
  model_config: "http://127.0.0.1:8000/getModelConfigbyId"
minio:
  endpoint: 172.16.0.170:9000
  secret_key: JEJG4oNT3rpTe80VlFXWcxkE8fWUVJfxP1XHdmNd
  access_key: XHXPHOuchiuxkQpYUYIM
  secure: False
 
