
apis:
  container: "http://10.0.153.141:8000/container"
  container_model: "http://10.0.153.141:8000/containermodel"
  update_endpoint: "http://10.0.153.141:8000/updateEndpoint"
  model_master_config: "http://10.0.153.141:8000/getModelMasterbyId"
  model_config: "http://10.0.153.141:8000/getModelConfigbyId"
minio:
  endpoint: http://10.0.153.141:9000
  secret_key: fz7x9AcpZqB7YY0VxgiQAYtC4RZVPSaumQycHPrP
  access_key: BIVeLI5sayqshgRWSm5H
  secure: False
 
